name: e_commerce
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.4.3
  cupertino_icons: ^1.0.2
  easy_stepper: ^0.3.2
  firebase_auth: ^4.2.9
  firebase_core: ^2.6.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_facebook_auth: ^5.0.7
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.2
  google_sign_in: ^6.0.0
  path: ^1.8.2
  shared_preferences: ^2.0.17
  sqflite: ^2.2.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
